### ISSUE TITLE
Add playbook example in README

### ISSUE THREAD

**Issue by giovannisciortino** [giovannisciortino/ansible-generate-report#1]
Create a example playbook for the README file

**Comment by NomakCooper** [comment]
I insert here an example of a simple task that generates the .xlsx report from the ansible CN 👍 

```yaml
  # create xlsx
  - name: generate xlsx report
    become: false
    xlswriter:
      csv_dir: /tmp/csv_dir
      output_xlsx_file: /tmp/csv_dir/full_report.xlsx
      format_header: True
    run_once: true  
    delegate_to: localhost
```

**Comment by NomakCooper** [comment]
Basic playbook "**Linux multipath report**". 
**shell -> csv -> xlsx**

```yaml
---
- name: Linux Check Multipath
  hosts: all
  gather_facts: no
  become: true
  become_method: sudo
  
  # Gather Fatc
  pre_tasks:

  - name: "Gather fact"
    setup:
      filter:
      - 'ansible_limit'
      - 'ansible_hostname'

  tasks:

  # create directory on localhost
  - name: Create directory on localhost
    become: false
    ansible.builtin.file:
      path: /tmp/check_multipath
      state: directory
    run_once: true
    delegate_to: localhost
    
  # check multipath
  - name: check multipath info
    shell: multipathd show paths format %d,%S,%t,%T,%o,%D,%i,%w,%N,%n,%R,%r
    register: multipathcmd

  # create report
  - name: create csv report
    become: false
    ansible.builtin.copy:
      dest: /tmp/check_multipath/{{ansible_hostname}}.csv
      content: |
        {% for line in multipathcmd.stdout_lines %}
        {{ line }}
        {% endfor %}
    delegate_to: localhost
    
  # create xls
  - name: generate xls report
    become: false
    xlswriter:
      csv_dir: /tmp/check_multipath
      output_xlsx_file: /tmp/check_multipath/multipath_report.xlsx
      format_header: True
    run_once: true  
    delegate_to: localhost                    
  ```

Need **XlsxWriter** module installation?

default install :
```yaml
  - name: Install XlsxWriter
    become: false
    ansible.builtin.pip:
      name: XlsxWriter
    delegate_to: localhost
```

copy and install via .whl file:

```yaml
  - name: Copy XlsxWriter python module
    become: false
    ansible.builtin.copy:
      src: "XlsxWriter-3.2.0-py3-none-any.whl"
      dest: /tmp/XlsxWriter-3.2.0-py3-none-any.whl
    delegate_to: localhost

  # install python module
  - name: Install XlsxWriter python module
    become: false
    ansible.builtin.pip:
      name: /tmp/XlsxWriter-3.2.0-py3-none-any.whl
    delegate_to: localhost
```
